
const Code = () => {
   const code = [
    { code: "+1" , name:" Canada"},
    { code: "+1" , name:" United States"},
    { code: "+1 340 ", name:" United States Virgin Islands"},
    { code: "+1 670 ", name:" Northern Mariana Islands"},
    { code: "+1 671 ", name:" Guam"},
    { code: "+1 684 ", name:" American Samoa"},
    { code: "+1 787 / 939" , name:" Puerto Rico"},
    { code: "+1 242 ", name:" Bahamas"},
    { code: "+1 246 ", name:" Barbados"},
    { code: "+1 264 ", name:" Anguilla"},
    { code: "+1 268 ", name:" Antigua and Barbuda"},
    { code: "+1 284 ", name:" British Virgin Islands"},
    { code: "+1 345 ", name:" Cayman Islands"},
    { code: "+1 441 ", name:" Bermuda"},
    { code: "+1 473 ", name:" Grenada"},
    { code: "+1 649 ", name:" Turks and Caicos Islands"},
    { code: "+1 658 / 876  ", name:" Jamaica"},
    { code: "+1 664 ", name:" Montserrat"},
    { code: "+1 721 ", name:" Sint Maarten"},
    { code: "+1 758 ", name:" Saint Lucia"},
    { code: "+1 767 ", name:" Dominica"},
    { code: "+1 784 ", name:" Saint Vincent and the Grenadines"},
    { code: "+1 809 / 829 / 849", name:" Dominican Republic"},
    { code: "+1 868 ", name:" Trinidad and Tobago"},
    { code: "+1 869 ", name:" Saint Kitts and Nevis"},
    { code: "+20" , name:" Egypt"},
    { code: "+211" , name:" South Sudan"},
    { code: "+212" , name:"Morocco (including Western Sahara)"},
    { code: "+213" , name:" Algeria"},
    { code: "+216" , name:" Tunisia"},
    { code: "+218" , name:" Libya"},
    { code: "+220" , name:" Gambia"},
    { code: "+221" , name:" Senegal"},
    { code: "+222" , name:" Mauritania"},
    { code: "+223" , name:" Mali"},
    { code: "+224" , name:" Guinea"},
    { code: "+225" , name:" Ivory Coast"},
    { code: "+226" , name:" Burkina Faso"},
    { code: "+227" , name:" Niger"},
    { code: "+228" , name:" Togo"},
    { code: "+229" , name:" Benin"},
    { code: "+230" , name:" Mauritius"},
    { code: "+231" , name:" Liberia"},
    { code: "+232" , name:" Sierra Leone"},
    { code: "+233" , name:" Ghana"},
    { code: "+234" , name:" Nigeria"},
    { code: "+235" , name:" Chad"},
    { code: "+236" , name:" Central African Republic"},
    { code: "+237" , name:" Cameroon"},
    { code: "+238" , name:" Cape Verde"},
    { code: "+239" , name:" São Tomé and Príncipe"},
    { code: "+240" , name:" Equatorial Guinea"},
    { code: "+241" , name:" Gabon"},
    { code: "+242" , name:" Republic of the Congo"},
    { code: "+243" , name:" Democratic Republic of the Congo"},
    { code: "+244" , name:" Angola"},
    { code: "+245" , name:" Guinea-Bissau"},
    { code: "+246" , name:" British Indian Ocean Territory"},
    { code: "+247" , name:" Ascension Island"},
    { code: "+248" , name:" Seychelles"},
    { code: "+249" , name:" Sudan"},
    { code: "+250" , name:" Rwanda"},
    { code: "+251" , name:" Ethiopia"},
    { code: "+252" , name:" Somalia"},
    { code: "+253" , name:" Djibouti"},
    { code: "+254" , name:" Kenya"},
    { code: "+255" , name:" Tanzania"},
    { code: "+255 24 " , name:"Zanzibar"},
    { code: "+256" , name:" Uganda"},
    { code: "+257" , name:" Burundi"},
    { code: "+258" , name:" Mozambique"},
    { code: "+260" , name:" Zambia"},
    { code: "+261" , name:" Madagascar"},
    { code: "+262" , name:" Réunion"},
    { code: "+263" , name:" Zimbabwe"},
    { code: "+264" , name:" Namibia"},
    { code: "+265" , name:" Malawi"},
    { code: "+266" , name:" Lesotho"},
    { code: "+267" , name:" Botswana"},
    { code: "+268" , name:" Eswatini"},
    { code: "+269" , name:" Comoros"},
    { code: "+27" , name:" South Africa"},
    { code: "+290" , name:" Saint Helena"},
    { code: "+290 8", name:" Tristan da Cunha"},
    { code: "+291" , name:" Eritrea"},
    { code: "+297" , name:" Aruba"},
    { code: "+298" , name:" Faroe Islands"},
    { code: "+299" , name:" Greenland"},
    {code: "+30" , name:" Greece"},
    {code: "+31" , name:" Netherlands"},
    {code: "+32" , name:" Belgium"},
    {code: "+33" , name:" France"},
    {code: "+34" , name:" Spain"},
    {code: "+350" , name:" Gibraltar"},
    {code: "+351" , name:" Portugal"},
    {code: "+352" , name:" Luxembourg"},
    {code: "+353" , name:" Ireland"},
    {code: "+354" , name:" Iceland"},
    {code: "+355" , name:" Albania"},
    {code: "+356" , name:" Malta"},
    {code: "+358" , name:" Finland"},
    {code: "+358 18"  , name:" Åland"},
    {code: "+359" , name:" Bulgaria"},
    {code: "+36" , name:" Hungary"},
    {code: "+370" , name:" Lithuania"},
    {code: "+371" , name:" Latvia"},
    {code: "+372" , name:" Estonia"},
    {code: "+373" , name:" Moldova"},
    {code: "+374" , name:" Armenia"},
    {code: "+374 47"  , name:" Artsakh"},
    {code: "+374 97"  , name:" Artsakh (mobile phones)"},
    {code: "+375" , name:" Belarus"},
    {code: "+376" , name:" Andorra"},
    {code: "+377" , name:" Monaco"},
    {code: "+378" , name:" San Marino"},
    {code: "+379" , name:" Vatican City"},
    {code: "+380" , name:" Ukraine"},
    {code: "+381" , name:" Serbia"},
    {code: "+382" , name:" Montenegro"},
    {code: "+383" , name:" Kosovo"},
    {code: "+385" , name:" Croatia"},
    {code: "+386" , name:" Slovenia"},
    {code: "+387" , name:" Bosnia and Herzegovina"},
    {code: "+389" , name:" North Macedonia"},
    {code: "+39" , name:" Italy"},
    {code: "+39 06 698"  , name:"  Vatican City"},
    { code: "+40" , name:" Romania"},
    { code: "+41" , name:"  Switzerland"},
    { code: "+420" , name:" Czech Republic"},
    { code: "+421" , name:" Slovakia"},
    { code: "+422" , name:"unassigned"},
    { code: "+423" , name:" Liechtenstein"},
    { code: "+43" , name:" Austria"},
    { code: "+44" , name:" United Kingdom"},
    { code: "+44 1481"  , name:" Guernsey"},
    { code: "+44 1534"  , name:" Jersey"},
    { code: "+44 1624"  , name:" Isle of Man"},
    { code: "+45" , name:" Denmark"},
    { code: "+46" , name:" Sweden"},
    { code: "+47" , name:" Norway"},
    { code: "+47 79"  , name:" Svalbard"},
    { code: "+48" , name:" Poland"},
    { code: "+49" , name:" Germany"},
    { code: "+500" , name:" Falkland Islands"},
    { code: "+501" , name:" Belize"},
    { code: "+502" , name:" Guatemala"},
    { code: "+503" , name:" El Salvador"},
    { code: "+504" , name:" Honduras"},
    { code: "+505" , name:" Nicaragua"},
    { code: "+506" , name:" Costa Rica"},
    { code: "+507" , name:" Panama"},
    { code: "+508" , name:" Saint-Pierre and Miquelon"},
    { code: "+509" , name:" Haiti"},
    { code: "+51" , name:" Peru"},
    { code: "+52" , name:" Mexico"},
    { code: "+53" , name:" Cuba"},
    { code: "+54" , name:" Argentina"},
    { code: "+55" , name:" Brazil"},
    { code: "+56" , name:" Chile"},
    { code: "+57" , name:" Colombia"},
    { code: "+58" , name:" Venezuela"},
    { code: "+591" , name:" Bolivia"},
    { code: "+592" , name:" Guyana"},
    { code: "+593" , name:" Ecuador"},
    { code: "+594" , name:" French Guiana"},
    { code: "+595" , name:" Paraguay"},
    { code: "+597" , name:" Suriname"},
    { code: "+598" , name:" Uruguay"},
    { code: "+599 3"  , name:" Sint Eustatius"},
    { code: "+599 4"  , name:" Saba"},
    { code: "+599 7"  , name:" Bonaire"},
    { code: "+599 9" , name:" Curaçao"},
    { code: "+60" , name:" Malaysia"},
    { code: "+61" , name:" Australia"},
    { code: "+61 8 9162"  , name:" Cocos Islands"},
    { code: "+61 8 9164 " , name:" Christmas Island"},
    { code: "+62" , name:" Indonesia"},
    { code: "+63" , name:" Philippines"},
    { code: "+64" , name:" New Zealand"},
    { code: "+65" , name:" Singapore"},
    { code: "+66" , name:" Thailand"},
    { code: "+670" , name:" East Timor"},
    { code: "+672" , name:"Australian External Territories"},
    { code: "+672 1x", name:"Australia Australian Antarctic Territory"},
    { code: "+672 3"  , name:" Norfolk Island"},
    { code: "+673" , name:" Brunei"},
    { code: "+674" , name:" Nauru"},
    { code: "+675" , name:" Papua New Guinea"},
    { code: "+676" , name:" Tonga"},
    { code: "+677" , name:" Solomon Islands"},
    { code: "+678" , name:" Vanuatu"},
    { code: "+679" , name:" Fiji"},
    { code: "+680" , name:" Palau"},
    { code: "+681" , name:" Wallis and Futuna"},
    { code: "+682" , name:" Cook Islands"},
    { code: "+683" , name:" Niue"},
    { code: "+685" , name:" Samoa"},
    { code: "+686" , name:" Kiribati"},
    { code: "+687" , name:" New Caledonia"},
    { code: "+688" , name:" Tuvalu"},
    { code: "+689" , name:" French Polynesia"},
    { code: "+690" , name:" Tokelau"},
    { code: "+691" , name:" Federated States of Micronesia"},
    { code: "+692" , name:" Marshall Islands"},
    { code: "+7" , name:" Russia"},
    { code: "+7 840 / 940 ", name:" Abkhazia"},
    { code: "+7 850 / 9298"  , name:" South Ossetia"},
    { code: "+81" , name:" Japan"},
    { code: "+82" , name:" South Korea"},
    { code: "+84" , name:" Vietnam"},
    { code: "+850" , name:" North Korea"},
    { code: "+852" , name:" Hong Kong"},
    { code: "+853" , name:" Macau"},
    { code: "+855" , name:" Cambodia"},
    { code: "+856" , name:" Laos"},
    { code: "+86" , name:" China"},
    { code: "+880" , name:" Bangladesh"},
    { code: "+886" , name:" Taiwan"},
    { code: "+90" , name:" Turkey"},
    { code: "+90 392"  , name:" Northern Cyprus"},
    { code: "+91" , name:" India"},
    { code: "+92" , name:" Pakistan"},
    { code: "+92 581"  , name:" Gilgit Baltistan[3]"},
    { code: "+92 582"  , name:" Azad Kashmir[3]"},
    { code: "+93" , name:" Afghanistan"},
    { code: "+94" , name:" Sri Lanka"},
    { code: "+95" , name:" Myanmar"},
    { code: "+960" , name:" Maldives"},
    { code: "+961" , name:" Lebanon"},
    { code: "+962" , name:" Jordan"},
    { code: "+963" , name:" Syria"},
    { code: "+964" , name:" Iraq"},
    { code: "+965" , name:" Kuwait"},
    { code: "+966" , name:" Saudi Arabia"},
    { code: "+967" , name:" Yemen"},
    { code: "+968" , name:" Oman"},
    { code: "+970" , name:" Palestine"},
    { code: "+971" , name:" United Arab Emirates"},
    { code: "+972" , name:" Israel"},
    { code: "+973" , name:" Bahrain"},
    { code: "+974" , name:" Qatar"},
    { code: "+975" , name:" Bhutan"},
    { code: "+976" , name:" Mongolia"},
    { code: "+977" , name:" Nepal"},
    { code: "+98" , name:" Iran"},
    { code: "+992" , name:" Tajikistan"},
    { code: "+993" , name:" Turkmenistan"},
    { code: "+994" , name:" Azerbaijan"},
    { code: "+995" , name:" Georgia"},
    { code: "+996" , name:" Kyrgyzstan"},
    { code: "+997" , name:" Kazakhstan"},
    { code: "+998" , name:" Uzbekistan"},
   ]

   return {code}
}

export default Code