export const types = {
  login: "[AUTH]login",
  logout: "[AUTH]logout",

  uiSetError: "[UI] Set Error",
  uiRemoveError: "[UI] Remove Error",
  uiStartLoading: "[UI] Start loading",
  uiFinishLoading: "[UI] Finish loading",
  uiActiveEnds: "[UI] active ends",

  serchList: "[SERCH] List",
  serchActive: "[SERCH] active",
  serchInactive: "[SERCH] desactive",
  emptySerch: "[SERCH] Empty",

  product: "[PRODUCT] List",
  productList: "[PRODUCT] List Config",
  productAdd: "[PRODUCT] Add",
  productEdit: "[PRODUCT] Edit",
  productDelete: "[PRODUCT] Delete",
  productActive: "[PRODUCT] Active",
  productRevert: "[PRODUCT] Inactive",
  productActiveCart: "[PRODUCT] Active Cart",
  productSaveCart: "[PRODUCT] Save Cart",
  productDeleteCart: "[PRODUCT] Delete Cart",
  productDeleteSave: "[PRODUCT] Delete Save",
  productSaveLatest: "[PRODUCT] Save Latest",
  productCategory: "[PRODUCT] Serch Category",
  productCategoryClose: "[PRODUCT] Close Category",
  productClose: "[PRODUCT] Close",

  active: "[DATA] Active",
  closeActive: "[DATA] Close",

  category: "[CATEGORY] List",
  categoryList: "[CATEGORY] List Config",
  categoryAdd: "[CATEGORY] Add",
  categoryEdit: "[CATEGORY] Edit",
  categoryDelete: "[CATEGORY] Delete",
  categoryActive: "[CATEGORY] Active",
  categoryActiveOld: "[CATEGORY] Old",
  categoryClose: "[CATEGORY] Close",

  userRol: "[ROL] roles",

  checkoutAdd: "[CHECKOUT] Add",
  checkoutList: "[CHECKOUT] List",
  checkoutDelete: "[CHECKOUT] Delete",
  cheListAllHistory: "[CHECKOUT] History",
  cheListAllActive: "[CHECKOUT] Active",
  cheClear: "[CHECKOUT] Clear",

  user: "[USER] List",
  userAdd: "[USER] Add",
  userEdit: "[USER] Edit",
  userDelete: "[USER] Delete",
  userActive: "[USER] Active",
};
